name: Publish Code Coverage

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Build Code Coverage
      run: composer cover
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.phpunit.cache/html
        destination_dir: code-coverage